# Generated by Django 3.2 on 2022-09-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220922_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='owner',
        ),
    ]
