# Generated by Django 3.2 on 2022-09-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_products_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('in the way', 'in the way'), ('deliverd', 'deliverd')], max_length=255, null=True),
        ),
    ]
