# Generated by Django 3.2 on 2022-09-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('in the way', 'in the way'), ('deliverd', 'deliverd')], default='pending', max_length=255, null=True),
        ),
    ]
