# Generated by Django 3.2 on 2022-09-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20220926_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('createdAt',)},
        ),
    ]
